name: dream_app
description: "AI-powered dream analysis mobile app"
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  intl: ^0.20.2
  provider: ^6.0.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true