services:
  - type: web
    name: dream-analyzer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /api/health 